<?php
// src/TricksBundle/Entity/TricksRepository.php

namespace TricksBundle\Repository;

/**
 * TricksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;

class TricksRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($id, $em)
    {
        $queryBuilder = $em->createQueryBuilder()
            ->select('u')
            ->from('TricksBundle:Comment', 'u')
            ->andWhere('u.tricks = :searchTerm')
            ->setParameter('searchTerm', $id);
        $adapter = new DoctrineORMAdapter($queryBuilder);



        return $adapter;
    }
}
