<?php
// src/TricksBundle/Entity/TricksRepository.php

namespace TricksBundle\Repository;

/**
 * TricksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TricksRepository extends \Doctrine\ORM\EntityRepository
{
}
