# src/TricksBundle/Resources/config/routing.yml

tricks_homepage:
    path:     /
    defaults: { _controller: TricksBundle:IndexTricks:index }

tricks_homepage:
    path:     tricks
    defaults: { _controller: TricksBundle:IndexTricks:index }

tricks_add:
    path:     tricks/add
    defaults: { _controller: TricksBundle:AddTricks:add }

tricks_edit:
    path:     tricks/edit/{id}
    defaults: { _controller: TricksBundle:EditTricks:edit }

tricks_delete:
    path:     tricks/delete/{id}
    defaults: { _controller: TricksBundle:DeleteTricks:delete }

tricks_view:
    path:      tricks/{id}
    defaults: { _controller: TricksBundle:ViewTricks:view }