# src/TricksBundle/Resources/config/routing.yml

tricks_homepage:
    path:     /
    defaults: { _controller: TricksBundle:Tricks:index }

tricks_homepage:
    path:     tricks
    defaults: { _controller: TricksBundle:Tricks:index }

tricks_add:
    path:     tricks/add
    defaults: { _controller: TricksBundle:Tricks:add }

tricks_edit:
    path:     tricks/edit/{id}
    defaults: { _controller: TricksBundle:Tricks:edit }

tricks_delete:
    path:     tricks/delete/{id}
    defaults: { _controller: TricksBundle:Tricks:delete }

tricks_view:
    path:      tricks/{id}
    defaults: { _controller: TricksBundle:Tricks:view }

fileUpload:
  path:       server/php/
  defaults: { _controller: web/js/fileUpload/server/php/index.php  }